version: '3'

volumes:
  postgresql-data:
    name: ${VOLUME_ID}

services:

  postgreSQL:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=workshop_app
    volumes:
      - postgresql-data:/var/lib/postgresql
    restart: unless-stopped

  myapp-main:
    build: .
    restart: on-failure
    depends_on:
      - postgreSQL
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=myapp-user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=workshop_app
      - DATABASE_PORT=3306
